<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Twitter Cards and Open Graph Tags -->
<meta property="twitter:card" content="summary" />
<meta property="og:title" content="Rent a Driveway" />
<meta property="og:type" content="website" />
<meta property="og:image" content="https://parking.ele.moe/assets/images/logo-l.png" />
<meta property="og:description" content="Rent a driveway or list your driveway on our peer to peer parking marketplace" />
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<!-- Favicon and app icons -->
<link rel="apple-touch-icon" sizes="180x180" href="https://parking.ele.moe/assets/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="https://parking.ele.moe/assets/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="https://parking.ele.moe/assets/favicon/favicon-16x16.png">
<link rel="manifest" href="https://parking.ele.moe/assets/favicon/site.webmanifest">
<link rel="mask-icon" href="https://parking.ele.moe/assets/favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="assets/css/main.css">
<script src="assets/js/jquery-3.3.1.slim.min.js"></script>
<script src="assets/js/main.js"></script>